In [1]:
import numpy as np

In [2]:
A = np.array([[3, 2], [4, 1]])
print(A)

[[3 2]
 [4 1]]


In [4]:
autovalores, autovectores = np.linalg.eig(A)

In [5]:
print(autovalores)
print(autovectores)

[ 5. -1.]
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


In [6]:
# utilizamos autovectores y autovalores para calcular nuestra matriz

A_calc = autovectores.dot(np.diag(autovalores)).dot(np.linalg.inv(autovectores))

In [7]:
print(A_calc)

[[3. 2.]
 [4. 1.]]


In [8]:
# en caso de que la matriz sea real y sim;étrica A=A.T

A = np.array([[3,2], [2,3]])
print(A)

[[3 2]
 [2 3]]


In [9]:
print(A==A.T)

[[ True  True]
 [ True  True]]


In [10]:
autovalores, autovectores = np.linalg.eig(A)
print(autovalores)
print(autovectores)

[5. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [11]:
A_calc = autovectores.dot(np.diag(autovalores)).dot(autovectores.T)
print(A_calc)

[[3. 2.]
 [2. 3.]]
